version: '3'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch 
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/config/plugins/IK:/usr/share/elasticsearch/plugins/ik:rw
        #  - ./elasticsearch/dataStore/master-data01:/usr/share/elasticsearch/data:rw
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - elk
 
  elasticsearch2:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch2
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/config/elasticsearch-node2.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
        #- ./elasticsearch/dataStore/node-data02:/usr/share/elasticsearch/data:rw
    ports:
      - "9202:9200"
    environment:
      ES_JAVA_OPTS: "-Xmx2048m -Xms2048m"
    networks:
      - elk

  elasticsearch3:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch3
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/config/elasticsearch-node3.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
        # - ./elasticsearch/dataStore/node-data03:/usr/share/elasticsearch/data:rw
    ports:
      - "9203:9200"
    environment:
      ES_JAVA_OPTS: "-Xmx4096m -Xms4096m"
    networks:
      - elk
 
  cerebro:
    image: yannart/cerebro
    container_name: cerebro
    ports:
      - "9000:9000"
    networks:
      - elk
    depends_on:
      - elasticsearch

  logstash:  
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logstash/DataSet:/usr/share/logstash/DataSet:ro
    ports:
      - "5001:5001"
      - "9600:9600"
      - "5555:5555"
    environment:
      LS_JAVA_OPTS: "-Xmx1024m -Xms1024m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: kibana
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    build:
      context: filebeat/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: filebeat
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
      - ./filebeat/DataSet:/usr/share/filebeat/DataSet:ro
    networks:
      - elk
    depends_on:
      - elasticsearch
      - kibana

networks:
  elk:
    driver: bridge
