ARG ELK_VERSION
# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana-oss:${ELK_VERSION}

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
#RUN kibana-plugin install https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/6.6.0/kibana-prometheus-exporter-6.6.0.zip
